"""Artifact-freshness gate: detect drift between committed artifacts and what
the pipeline would produce today.

Regenerates EVERY committed generated artifact — the 10 publish JSONs,
forecast.json (trained model), src/data/generated/geo/land.json (geometry),
and docs/data-quality-report.md (quality report) — into a temporary location
and compares byte-for-byte against the committed files.

Normalisation rules (so wall-clock timestamps don't trigger false positives):
  - JSON artifacts with a top-level ``generatedAt`` key: that field is replaced
    with a fixed sentinel on both sides before comparing.
  - docs/data-quality-report.md: the "Generated … on YYYY-MM-DD …" line is
    replaced with a fixed sentinel on both sides.

Exits non-zero if any artifact differs or is missing.

This is a deliberate RELEASE / CI check, NOT a routine pytest — it requires
the DuckDB warehouse and data-raw/ to be present, and it takes O(seconds).
Do NOT invoke it from the normal test suite.

Usage:
    .venv/bin/python pipeline/check_freshness.py
    .venv/bin/python pipeline/check_freshness.py --db path/to/mobi.duckdb

Expected on a clean rebuild: exits 0.
Expected after SQL changes without a rebuild: exits 1 and lists the drifted files.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path

import duckdb

import common
import publish
import geo_publish
import quality_report
import train_model

_GENERATED_AT_SENTINEL = "__FRESHNESS_CHECK__"
_REPORT_DATE_RE = re.compile(
    r"(Generated by `pipeline/quality_report\.py` on )\d{4}-\d{2}-\d{2}( )"
)
_REPORT_DATE_SENTINEL = r"\g<1>__FRESHNESS_CHECK__\g<2>"


def _normalize_json(path: Path) -> bytes:
    """Return comparable bytes for a JSON artifact.

    If the JSON contains a top-level ``generatedAt`` key (a wall-clock date
    that changes on every run), replace it with a fixed sentinel on both the
    committed and freshly-generated side before comparing.  All other artifacts
    are compared byte-for-byte unchanged.
    """
    raw = path.read_bytes()
    try:
        obj = json.loads(raw)
    except json.JSONDecodeError:
        return raw
    if isinstance(obj, dict) and "generatedAt" in obj:
        obj["generatedAt"] = _GENERATED_AT_SENTINEL
        return json.dumps(obj, ensure_ascii=False, sort_keys=True).encode()
    return raw


def _normalize_report(text: str) -> str:
    """Replace the wall-clock date in the quality report header."""
    return _REPORT_DATE_RE.sub(_REPORT_DATE_SENTINEL, text, count=1)


# Keep the old name as an alias so any external callers still work.
_normalize_bytes = _normalize_json

COMMITTED_DIR = common.REPO_ROOT / "src" / "data" / "generated"
COMMITTED_GEO = COMMITTED_DIR / "geo"
COMMITTED_REPORT = common.REPO_ROOT / "docs" / "data-quality-report.md"
WAREHOUSE_DEFAULT = common.REPO_ROOT / "data-warehouse" / "mobi.duckdb"

# Artifacts produced by publish.build_artifacts (warehouse → JSON).
PUBLISH_NAMES = {f.name for f in COMMITTED_DIR.glob("*.json")} - {"forecast.json"}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--db", type=Path, default=WAREHOUSE_DEFAULT,
        help="DuckDB warehouse path (default: data-warehouse/mobi.duckdb)",
    )
    args = parser.parse_args()

    if not args.db.exists():
        print(
            f"error: warehouse not found at {args.db}\n"
            "Run the full pipeline first: python pipeline/etl.py --stage all",
            file=sys.stderr,
        )
        return 2

    drifted: list[str] = []

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)

        # ------------------------------------------------------------------ #
        # 1. Publish JSONs (warehouse → 10 × *.json)
        # ------------------------------------------------------------------ #
        print(f"Regenerating publish artifacts from {args.db} …")
        con = duckdb.connect(str(args.db))
        con.execute("SET VARIABLE data_raw = ?", [str(common.DATA_RAW)])
        con.execute(
            (common.PIPELINE_DIR / "sql" / "50_publish.sql").read_text(encoding="utf-8")
        )
        artifacts = publish.build_artifacts(con)
        con.close()
        publish.write_artifacts(artifacts, tmp_dir)

        committed_names = {f.name for f in COMMITTED_DIR.glob("*.json")} - {"forecast.json"}
        generated_names = {f.name for f in tmp_dir.glob("*.json")}

        for name in sorted(committed_names | generated_names):
            committed = COMMITTED_DIR / name
            generated = tmp_dir / name
            if not committed.exists():
                print(f"  MISSING in committed:  {name}")
                drifted.append(name)
            elif not generated.exists():
                print(f"  MISSING in generated:  {name}")
                drifted.append(name)
            elif _normalize_json(committed) != _normalize_json(generated):
                print(f"  DRIFT:                 {name}")
                drifted.append(name)
            else:
                print(f"  ok                     {name}")

        # ------------------------------------------------------------------ #
        # 2. forecast.json (train_model — deterministic gradient-boosted fit)
        # ------------------------------------------------------------------ #
        print("\nRegenerating forecast.json …")
        tmp_forecast = tmp_dir / "forecast.json"
        # train_model writes to OUT (the committed path); redirect via monkeypatching
        _orig_out = train_model.OUT
        train_model.OUT = tmp_forecast
        try:
            train_model.main()
        finally:
            train_model.OUT = _orig_out

        committed_fc = COMMITTED_DIR / "forecast.json"
        if not committed_fc.exists():
            print(f"  MISSING in committed:  forecast.json")
            drifted.append("forecast.json")
        elif not tmp_forecast.exists():
            print(f"  MISSING in generated:  forecast.json")
            drifted.append("forecast.json")
        elif tmp_forecast.read_bytes() != committed_fc.read_bytes():
            print(f"  DRIFT:                 forecast.json")
            drifted.append("forecast.json")
        else:
            print(f"  ok                     forecast.json")

        # ------------------------------------------------------------------ #
        # 3. geo/land.json (Douglas-Peucker simplification — deterministic)
        # ------------------------------------------------------------------ #
        print("\nRegenerating geo/land.json …")
        tmp_geo = tmp_dir / "land.json"
        ring = geo_publish.build_land_ring()
        lons = [p[0] for p in ring]
        lats = [p[1] for p in ring]
        geo_payload = {
            "source": "City of Vancouver Open Data, shoreline-2002 (Open Government Licence - Vancouver)",
            "bounds": {
                "lonMin": min(lons), "lonMax": max(lons),
                "latMin": min(lats), "latMax": max(lats),
            },
            "landRing": ring,
        }
        geo_blob = json.dumps(geo_payload, separators=(",", ":")).encode("utf-8")
        tmp_geo.write_bytes(geo_blob + b"\n")

        committed_geo = COMMITTED_GEO / "land.json"
        if not committed_geo.exists():
            print(f"  MISSING in committed:  geo/land.json")
            drifted.append("geo/land.json")
        elif not tmp_geo.exists():
            print(f"  MISSING in generated:  geo/land.json")
            drifted.append("geo/land.json")
        elif tmp_geo.read_bytes() != committed_geo.read_bytes():
            print(f"  DRIFT:                 geo/land.json")
            drifted.append("geo/land.json")
        else:
            print(f"  ok                     geo/land.json")

        # ------------------------------------------------------------------ #
        # 4. docs/data-quality-report.md (warehouse → Markdown)
        # ------------------------------------------------------------------ #
        print("\nRegenerating docs/data-quality-report.md …")
        con2 = duckdb.connect(str(args.db), read_only=True)
        fresh_report = quality_report.build(con2)
        con2.close()

        tmp_report = tmp_dir / "data-quality-report.md"
        tmp_report.write_text(fresh_report, encoding="utf-8")

        if not COMMITTED_REPORT.exists():
            print(f"  MISSING in committed:  docs/data-quality-report.md")
            drifted.append("docs/data-quality-report.md")
        elif not tmp_report.exists():
            print(f"  MISSING in generated:  docs/data-quality-report.md")
            drifted.append("docs/data-quality-report.md")
        elif _normalize_report(COMMITTED_REPORT.read_text(encoding="utf-8")) != \
                _normalize_report(tmp_report.read_text(encoding="utf-8")):
            print(f"  DRIFT:                 docs/data-quality-report.md")
            drifted.append("docs/data-quality-report.md")
        else:
            print(f"  ok                     docs/data-quality-report.md")

    if drifted:
        print(
            f"\nFAIL: {len(drifted)} artifact(s) differ from the pipeline output.\n"
            "Re-run the relevant pipeline steps to regenerate:\n"
            "  python pipeline/publish.py\n"
            "  python pipeline/train_model.py\n"
            "  python pipeline/geo_publish.py\n"
            "  python pipeline/quality_report.py\n"
            "Then commit the updated artifacts.",
            file=sys.stderr,
        )
        return 1

    print("\nPASS: all committed artifacts match the pipeline output.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
