"""Verify the downloaded archive and write data-raw/inventory.md.

Checks that fail the run: gaps in the 2018-present monthly range, files under
100 KB, formats outside {csv, xlsx}, checksum mismatches against the manifest,
and duplicate checksums across periods.

Usage: python pipeline/inventory.py
"""

from __future__ import annotations

import re
import sys
import zipfile
from pathlib import Path

import common

MIN_BYTES = 100_000
DIMENSION_RE = re.compile(rb'<dimension ref="A1:[A-Z]+(\d+)"')


def count_csv_rows(path: Path) -> int:
    """Data rows in a CSV (line count minus header). Handles \n, \r\n, and
    the bare-\r line endings found in some 2020 exports."""
    lf = cr = 0
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            lf += chunk.count(b"\n")
            cr += chunk.count(b"\r")
    return max(max(lf, cr) - 1, 0)


def count_xlsx_rows(path: Path) -> int:
    """Data rows in sheet1 via the worksheet dimension, without loading cells."""
    with zipfile.ZipFile(path) as archive:
        sheet = archive.read("xl/worksheets/sheet1.xml")
    match = DIMENSION_RE.search(sheet)
    if match:
        return int(match.group(1)) - 1
    from openpyxl import load_workbook  # slow fallback, rarely needed

    book = load_workbook(path, read_only=True)
    rows = (book.active.max_row or 1) - 1
    book.close()
    return rows


def collect(manifest: dict) -> tuple[list[dict], list[str]]:
    """Gather per-file facts and every failed check."""
    records, issues = [], []
    trips = manifest["trips"]

    for period in common.expected_periods(trips):
        if period not in trips:
            issues.append(f"missing period: {period}")

    seen_hashes: dict[str, str] = {}
    for period, entry in sorted(trips.items()):
        fmt = entry.get("format")
        if not fmt:
            issues.append(f"{period}: never downloaded (no format recorded)")
            continue
        if fmt not in ("csv", "xlsx"):
            issues.append(f"{period}: unexpected format {fmt}")
            continue
        path = common.trip_file_path(period, fmt)
        if not path.exists():
            issues.append(f"{period}: file missing at {path.name}")
            continue
        size = path.stat().st_size
        if size < MIN_BYTES:
            issues.append(f"{period}: suspiciously small ({size:,} bytes)")
        sha = common.sha256_file(path)
        if sha != entry.get("sha256"):
            issues.append(f"{period}: checksum mismatch with manifest")
        if sha in seen_hashes:
            issues.append(f"{period}: duplicate content of {seen_hashes[sha]}")
        seen_hashes[sha] = period
        rows = count_csv_rows(path) if fmt == "csv" else count_xlsx_rows(path)
        records.append(
            {"period": period, "format": fmt, "bytes": size, "rows": rows, "sha256": sha}
        )
    return records, issues


def write_report(records: list[dict], issues: list[str], manifest: dict) -> None:
    total_rows = sum(r["rows"] for r in records)
    total_bytes = sum(r["bytes"] for r in records)
    lines = [
        "# Raw Data Inventory",
        "",
        f"Generated by `pipeline/inventory.py`. {len(records)} trip files, "
        f"{total_rows:,} raw rows, {total_bytes / 1e6:,.0f} MB.",
        "",
        "| Period | Format | MB | Rows | SHA-256 (first 12) |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    lines += [
        f"| {r['period']} | {r['format']} | {r['bytes'] / 1e6:.1f} "
        f"| {r['rows']:,} | `{r['sha256'][:12]}` |"
        for r in records
    ]
    lines += ["", "## Reference snapshots", ""]
    for key, ref in manifest.get("reference", {}).items():
        if "file" in ref:
            lines.append(f"- `{ref['file']}` ({ref['bytes']:,} bytes, fetched {ref['fetched_at']})")
        else:
            # Non-file references (e.g. ec_weather records a station + year range).
            detail = ", ".join(f"{k}={v}" for k, v in sorted(ref.items()))
            lines.append(f"- `{key}` ({detail})")
    if issues:
        lines += ["", "## Issues", ""] + [f"- {issue}" for issue in issues]
    (common.DATA_RAW / "inventory.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    manifest = common.load_manifest()
    records, issues = collect(manifest)
    write_report(records, issues, manifest)
    print(f"{len(records)} files inventoried -> {common.DATA_RAW / 'inventory.md'}")
    for issue in issues:
        print(f"ISSUE: {issue}", file=sys.stderr)
    return 1 if issues else 0


if __name__ == "__main__":
    sys.exit(main())
