"""Generate docs/data-quality-report.md from the warehouse.

Every number in the report is queried, never hand-written. Regenerate after
any ETL run: python pipeline/quality_report.py

Usage: python pipeline/quality_report.py [--db PATH] [--out PATH]
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import duckdb

import common

REPORT = common.REPO_ROOT / "docs" / "data-quality-report.md"


def q(con, sql: str):
    return con.execute(sql).fetchall()


def q1(con, sql: str):
    return con.execute(sql).fetchone()[0]


def metrics(con) -> dict:
    return {(s, m): v for s, m, v in q(con, "SELECT stage, metric, value FROM etl_metrics")}


def build(con) -> str:
    m = metrics(con)
    landed = m[("extract", "rows_landed")]
    kept = m[("clean", "rows_kept")]
    first_month = q1(con, "SELECT min(trip_month) FROM fact_trips")
    window_end = q1(
        con, "SELECT max(source_period) FROM fact_trips WHERE source_period <> '2017'"
    )

    lines = [
        "# Data Quality Report",
        "",
        f"Generated by `pipeline/quality_report.py` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')} against the DuckDB warehouse. "
        f"Source window: {first_month} to {window_end} (the last published source month; "
        "a handful of spillover rows depart later and are held back).",
        "",
        "## Pipeline funnel",
        "",
        "| Stage | Rows | Notes |",
        "| --- | ---: | --- |",
        f"| Landed (extract) | {landed:,} | {m[('extract', 'files_landed')]} source files |",
        f"| Dropped: both station names blank | {m[('clean', 'rows_dropped_blank_stations')]:,} "
        "| mostly cable-lock / non-dock events |",
        f"| Dropped: unparseable timestamp | {m[('clean', 'rows_dropped_bad_timestamp')]:,} "
        "| includes literal `1900-01-00 0:00` never-returned sentinels |",
        f"| Dropped: exact duplicates | {m[('clean', 'rows_dropped_duplicates')]:,} "
        "| spillover trips repeated across neighbouring monthly files |",
        f"| Kept (fact_trips) | {kept:,} | {100 * kept / landed:.1f}% of landed |",
        "",
        "## Quality flags (kept but flagged, not dropped)",
        "",
        f"{m[('conform', 'rows_flagged')]:,} trips "
        f"({100 * m[('conform', 'rows_flagged')] / kept:.1f}%) carry at least one flag. "
        "Published aggregates exclude a flag only where it invalidates the measure.",
        "",
        "| Flag | Trips |",
        "| --- | ---: |",
    ]
    for flag, count in q(
        con,
        """SELECT flag, count(*) FROM (SELECT unnest(quality_flags) AS flag FROM fact_trips)
           GROUP BY 1 ORDER BY 2 DESC""",
    ):
        lines.append(f"| `{flag}` | {count:,} |")

    coord_cov = q1(
        con,
        """SELECT 100.0 * sum(CASE WHEN s.lat IS NOT NULL THEN 1 ELSE 0 END) / count(*)
           FROM fact_trips f LEFT JOIN dim_station s ON f.departure_station_id = s.station_id""",
    )
    with_coords = q1(con, "SELECT count(*) FROM dim_station WHERE lat IS NOT NULL")
    total_stations = q1(con, "SELECT count(*) FROM dim_station")
    lines += [
        "",
        "## Station resolution",
        "",
        f"- {total_stations} station IDs appear in nine years of trips; "
        f"{with_coords} resolve to coordinates in the current GBFS feed. "
        "The remainder are retired stations kept in `dim_station` without geometry.",
        f"- {coord_cov:.1f}% of trips depart from a station with known coordinates.",
        "",
        "## Membership mapping",
        "",
    ]
    unmapped = q(con, "SELECT membership_raw FROM dim_membership WHERE membership_group IS NULL")
    labels = q1(con, "SELECT count(*) FROM dim_membership")
    lines.append(
        f"{labels} distinct raw labels observed (including a literal `None`) map to "
        "reporting groups via `pipeline/mappings/membership_groups.csv`:"
    )
    lines += ["", "| Group | Trips |", "| --- | ---: |"]
    for group, count in q(
        con,
        """SELECT coalesce(m.membership_group, 'Blank / Unknown (no label in source)'),
                  count(*)
           FROM fact_trips f LEFT JOIN dim_membership m USING (membership_raw)
           GROUP BY 1 ORDER BY 2 DESC""",
    ):
        lines.append(f"| {group} | {count:,} |")
    if unmapped:
        lines += ["", "**Unmapped labels needing a mapping decision:**"] + [
            f"- `{u[0]}`" for u in unmapped
        ]
    else:
        lines += ["", "No unmapped labels."]

    last_source_month = window_end
    countable = q1(
        con,
        """SELECT count(*) FROM fact_trips f
           LEFT JOIN dim_membership m USING (membership_raw)
           WHERE coalesce(m.membership_group, 'Unknown') <> 'Operations'
             AND f.trip_month <= '"""
        + last_source_month
        + """'
             AND NOT list_has_any(f.quality_flags,
                   ['round_trip_false_start', 'zero_duration', 'negative_duration'])""",
    )
    spillover_tail = q1(
        con, f"SELECT count(*) FROM fact_trips WHERE trip_month > '{last_source_month}'"
    )
    lines += [
        "",
        "## Analytic bases (reconciliation with the dashboard)",
        "",
        "Two row counts appear in this project and they are deliberately different:",
        "",
        f"- **Warehouse fact rows: {kept:,}** — every kept trip, flags and all. "
        "The tables in this report use this basis.",
        f"- **Dashboard countable trips: {countable:,}** — the published ridership "
        "basis: excludes `Operations` staff riding and trips flagged "
        "`round_trip_false_start`, `zero_duration`, or `negative_duration`, and is "
        f"capped at the last complete source month ({last_source_month}). "
        f"{spillover_tail:,} spillover rows depart after that month and are held "
        "back until their month's file is published.",
        "",
        "## Trips per month (fact rows, spillover-corrected)",
        "",
        "A trip's canonical month is its **departure** month; monthly source files "
        "contain trips from neighbouring months, deduplicated across files in the "
        "clean stage. Capped at the last published source month.",
        "",
        "| Month | Trips | | Month | Trips |",
        "| --- | ---: | --- | --- | ---: |",
    ]
    monthly = q(
        con,
        f"SELECT trip_month, count(*) FROM fact_trips WHERE trip_month <= '{last_source_month}' "
        "GROUP BY 1 ORDER BY 1",
    )
    half = (len(monthly) + 1) // 2
    for i in range(half):
        left = f"| {monthly[i][0]} | {monthly[i][1]:,} |"
        right = (
            f" {monthly[i + half][0]} | {monthly[i + half][1]:,} |"
            if i + half < len(monthly)
            else " | |"
        )
        lines.append(left + right)

    lines += [
        "",
        "## Source-format drift handled by the pipeline",
        "",
        "- 31 distinct header layouts across 102 files, unified by an explicit era map "
        "(`pipeline/mappings/column_eras.json`); unknown headers abort the run.",
        "- Header spelling drift includes `Memebership type`, `Electric`/`Electric Bike`, "
        "five temperature spellings, and the mojibake `Return temperature (Â°C)`.",
        "- Five timestamp shapes: Excel serials (2017), ISO with and without seconds, "
        "April 2019's `M/D/YY H:MM` (the only minute-precision file), and "
        "May 2025's `YYYY/MM/DD HH:MM:SS`.",
        "- Physical formats: XLSX (2017), CSV, Google-Sheets-hosted months (Oct 2022), "
        "UTF-8-BOM + bare-CR line endings (three 2020 files), and three summer 2023 "
        "files with invalid UTF-8 bytes in the Squamish-language station name "
        "šxʷƛ̓ənəq Xwtl'e7énḵ Square (transcoded, preserving rows).",
        "- The source page misspells the November 2021 link (`Novemeber 2021`) and "
        "carries an unlabeled duplicate of the 2017 export.",
        "- From mid-2025 the files write `0` instead of null for missing "
        "temperatures; those trips carry the `temp_suspect_zero` flag and are "
        "excluded from weather measures.",
        "",
        "## Known limitations",
        "",
        "- Timestamps are rounded to the nearest hour at source for rider privacy "
        "(except April 2019); time-of-day analysis has +/-30 minute precision.",
        "- Mobi excludes its own rebalancing trips before publishing; a small "
        "`Maintenance` membership remains and is grouped as `Operations`, excluded "
        "from ridership aggregates.",
        "- No rider demographics or route geometry exist in the source; distances "
        "are odometer-style per bike, not path measurements.",
        "- Retired stations have no public coordinate record; their trips count in "
        "totals but not in geographic views.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=common.REPO_ROOT / "data-warehouse" / "mobi.duckdb")
    parser.add_argument("--out", type=Path, default=REPORT)
    args = parser.parse_args()
    con = duckdb.connect(str(args.db), read_only=True)
    args.out.write_text(build(con), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
