-- Stage 10: landing zone. One row per raw source row, every value VARCHAR,
-- headers already unified by the era map (pipeline/mappings/column_eras.json).
-- Per-file INSERTs are generated by etl.py because each file's SELECT list
-- depends on its observed header layout.

CREATE OR REPLACE TABLE raw_trips (
  source_period    VARCHAR NOT NULL,  -- '2017' or 'YYYY-MM' (file the row came from)
  source_file      VARCHAR NOT NULL,
  departure        VARCHAR,
  "return"         VARCHAR,
  bike             VARCHAR,
  electric_bike    VARCHAR,
  departure_station VARCHAR,
  return_station   VARCHAR,
  membership       VARCHAR,
  distance_m       VARCHAR,
  duration_s       VARCHAR,
  stopover_s       VARCHAR,
  stopover_count   VARCHAR,
  departure_temp   VARCHAR,
  return_temp      VARCHAR
);

CREATE TABLE IF NOT EXISTS etl_metrics (
  stage  VARCHAR NOT NULL,
  metric VARCHAR NOT NULL,
  value  BIGINT  NOT NULL
);
DELETE FROM etl_metrics;
